#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if ! command -v php >/dev/null 2>&1; then
  echo "PHP is required to verify the theme." >&2
  exit 1
fi

required_files=(
  404.php
  archive.php
  assets/css/site.css
  assets/js/site.js
  footer.php
  front-page.php
  functions.php
  header.php
  index.php
  page-info.php
  page.php
  search.php
  searchform.php
  single.php
  style.css
  theme.json
)

for required_file in "${required_files[@]}"; do
  if [[ ! -f "$required_file" ]]; then
    echo "Missing required theme file: $required_file" >&2
    exit 1
  fi
done

while IFS= read -r php_file; do
  php -l "$php_file" >/dev/null
done < <(find . -type f -name '*.php' -not -path './vendor/*' -not -path './dist/*' | sort)

php -r '
$data = json_decode(file_get_contents("theme.json"), true, 512, JSON_THROW_ON_ERROR);
if (($data["version"] ?? null) !== 2) {
    fwrite(STDERR, "theme.json must use schema version 2.\n");
    exit(1);
}
'

if ! grep -q '^Text Domain: atomic-wp-starter$' style.css; then
  echo "Theme text domain is missing or inconsistent." >&2
  exit 1
fi

theme_version="$(sed -n 's/^Version: //p' style.css | head -n 1)"
if [[ -z "$theme_version" ]] || ! grep -Fq "define( 'ATOMIC_WP_STARTER_VERSION', '$theme_version' );" functions.php; then
  echo "Theme version is missing or inconsistent between style.css and functions.php." >&2
  exit 1
fi

residue_found=0
while IFS= read -r public_file; do
  if grep -Eni '(chatgpt|claude|codex|generated by ai|co-authored-by:)' "$public_file"; then
    residue_found=1
  fi
done < <(
  find . -type f \
    \( -name '*.php' -o -name '*.css' -o -name '*.js' -o -name '*.json' -o -name '*.md' -o -name '*.yml' -o -name '*.xml' -o -name '*.sh' \) \
    ! -path './vendor/*' \
    ! -path './dist/*' \
    ! -path './REVIEW.md' \
    ! -path './scripts/verify.sh' \
    -print
)

if [[ "$residue_found" -eq 1 ]]; then
  echo "Tool-specific or generated-code residue found in public theme files." >&2
  exit 1
fi

if find . -type f \( -name '*.sql' -o -name '.env' -o -name 'wp-config.php' \) -not -path './vendor/*' -print -quit | grep -q .; then
  echo "A sensitive or environment-specific file is present." >&2
  exit 1
fi

echo "Theme verification passed."
